### ISSUE TITLE
Relationship mutations are not generated

### ISSUE THREAD

**Issue by al-jeyapal** [neo4j-graphql/neo4j-graphql-java#73]
Hello,

Running through the following example does not seem to produce relationship mutations (e.g. `addPersonMovies`). Is there a step we are missing?

Schema:
```
type Movie  {
  title: ID!
  released: Int
  tagline: String
  actors: [Person] @relation(name:"ACTED_IN",direction:IN)
}
type Person {
  name: ID!
  born: Int
  movies: [Movie] @relation(name:"ACTED_IN")
}
```

Java Code:
```
final String schema = # read in above schema
final GraphQLSchema graphQLSchema =
                    SchemaBuilder.buildSchema(
                            schema, new Translator.Context());
translator = new Translator(graphQLSchema);

logger.debug("Available GraphQL Queries: [{}]",
        graphQLSchema.getQueryType().getFieldDefinitions().stream().map(
                GraphQLFieldDefinition::getName).collect(Collectors.joining(", ")));
# -> Available GraphQL Queries: [person, movie]

logger.debug("Available GraphQL Mutations: [{}]",
        graphQLSchema.getMutationType().getFieldDefinitions().stream().map(
                GraphQLFieldDefinition::getName).collect(Collectors.joining(", ")));
# -> Available GraphQL Mutations: [createPerson, updatePerson, deletePerson, createMovie, updateMovie, deleteMovie]

translator.translate("mutation { addPersonMovies(id: \"Kevin Bacon\", movies: [\"The Matrix\") { title actors { name }");
# -> throws exception
```

Exception:
```
java.lang.IllegalArgumentException: Unknown Query addPersonMovies available queries: person, movie
! at org.neo4j.graphql.Translator.toQuery(Translator.kt:47)
! at org.neo4j.graphql.Translator.translate(Translator.kt:38)
! at org.neo4j.graphql.Translator.translate$default(Translator.kt:31)
! at org.neo4j.graphql.Translator.translate(Translator.kt)
```

Is there something additional/different we need to do to have the auto-generated mutations (`addPersonMovies`, `deletePersonMovies`, `addMovieActors`, `deleteMovieActors`) available?

**Comment by al-jeyapal** [comment]
Resolved. The issue was due to using the older version of the library `1.0.0-M02` instead of `1.0.0-M03`.
It might be worth updating the `README` since that still references `1.0.0-M02`.
